language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - jruby-9.2.6.0
gemfile:
  - gemfiles/ar60.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.2.6.0
services:
  - postgres
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts
env:
  global:
    - PGVER=12
    - PGPORT=5432
before_install:
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
