language: ruby
gemfile:
  - gemfiles/ar60.gemfile
matrix:
  include:
    - rvm: 2.7
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10-postgis-2.4
            - postgresql-10-postgis-2.4-scripts
            - postgresql-client-10
      env:
        - PGPORT=5432
    - rvm: 2.7
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10-postgis-3
            - postgresql-10-postgis-3-scripts
            - postgresql-client-10
      env:
        - PGPORT=5432
    - rvm: 2.7
      addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-11-postgis-3
            - postgresql-11-postgis-3-scripts
      env:
        - PGPORT=5433
      before_install:
        - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
        - sudo pg_ctlcluster 11 main restart
    - rvm: 2.7
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-12-postgis-3
            - postgresql-12-postgis-3-scripts
      env:
        - PGPORT=5433
      before_install:
        - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
        - sudo pg_ctlcluster 12 main restart
  allow_failures:
    - rvm: jruby-9.2.6.0
services:
  - postgresql
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
