language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - jruby-9.2.6.0
gemfile:
  - gemfiles/ar60.gemfile
matrix:
  include:
    - addons:
      postgresql: "10"
      apt:
        packages:
          - postgresql-10-postgis-2.4
          - postgresql-10-postgis-2.4-scripts
          - postgresql-client-10
    - addons:
      postgresql: "10"
      apt:
        packages:
          - postgresql-10-postgis-3
          - postgresql-10-postgis-3-scripts
          - postgresql-client-10
    - addons:
      postgresql: "11"
      apt:
        packages:
          - postgresql-11
          - postgresql-client-11
          - postgresql-11-postgis-3
          - postgresql-11-postgis-3-scripts
    - addons:
      postgresql: "12"
      apt:
        packages:
          - postgresql-12
          - postgresql-client-12
          - postgresql-12-postgis-3
          - postgresql-12-postgis-3-scripts
  allow_failures:
    - rvm: jruby-9.2.6.0
env:
  global:
    - PGPORT=5433
services:
  - postgresql
before_script:
  - psql --version
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/$PGVER/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
