name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:${{ matrix.pg }}
        ports:
          - 5432:5432
    strategy:
      matrix:
        ruby: [2.7, 2.6, 2.5]
        BUNDLE_GEMFILE:
          - gemfiles/ar60.gemfile
        pg: [9, 10, 11, 12, 13]
        os: ["ubuntu-latest"]
    steps:
      - name: Set Up Gems
        uses: actions/checkout@v2
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install PostGIS
        run: sudo apt-get install postgresql-${{matrix.pg}}-postgis-3
      - name: Create DB and PostGIS Extension
        run: |
          psql -U postgres -c "create database postgis_adapter_test"
          psql -U postgres -d postgis_adapter_test -c "create extension postgis"
        env:
          PGHOST: localhost
      - name: Run Tests
        run: bundle exec rake test
